<?php

class Post extends CI_Model{

    private $aryData = [
        'title' => null,
        'content' => null,
        'datetime' => null,
        'category' => null,
    ];


    public function __construct($id = null)
    {
        if(!empty($id)){
            // Search for id in database
            // set
        }
    }

    public function __get($key)
    {
        return parent::__get($key); // TODO: Change the autogenerated stub
    }

    public function getId(){

    }

    public function getTitle(){

    }

    public function getContent(){

    }

    public function getAuthor(){

    }

    public function getDateTime(){

    }

    public function getCategory(){

    }

    public function save(){

    }

    public function getById($id){
        if(!empty($id)){

        }
    }



}